# Generated by Django 6.0.6 on 2026-06-27 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('session_reminder', 'Upcoming Study Session'), ('study_reminder', 'Reminder to Study'), ('new_match', 'New Study Partner Found'), ('group_activity', 'Group Activity'), ('message', 'New Message'), ('system', 'System')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, help_text='Frontend route to navigate to, e.g. /matches/12', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
