# Generated by Django 6.0.6 on 2026-06-27 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='Overall compatibility score, 0-100')),
                ('subject_score', models.FloatField(default=0)),
                ('department_score', models.FloatField(default=0)),
                ('year_score', models.FloatField(default=0)),
                ('schedule_score', models.FloatField(default=0)),
                ('skill_level_score', models.FloatField(default=0)),
                ('goal_score', models.FloatField(default=0)),
                ('language_score', models.FloatField(default=0)),
                ('common_subjects', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='suggested', max_length=10)),
                ('student1_responded', models.BooleanField(default=False)),
                ('student2_responded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_student1', to=settings.AUTH_USER_MODEL)),
                ('student2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_student2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
                'unique_together': {('student1', 'student2')},
            },
        ),
    ]
